"""shared_foundation"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "b3194d72d2b4"
down_revision = "0001_security_tables"
branch_labels = None
depends_on = None


def upgrade():
    # Preserve P2's pre-integration tables in an archive schema. Their indexes and
    # FK targets move with them; the public schema then has one canonical model.
    op.execute("CREATE SCHEMA IF NOT EXISTS legacy_security")
    for table in ("eligibility_grants", "sessions", "access_credentials", "users"):
        op.execute(f"ALTER TABLE {table} SET SCHEMA legacy_security")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("role IN ('participant','organizer','admin')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "access_credentials",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("digest", sa.String(length=128), nullable=False),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("digest"),
    )
    op.create_index(
        op.f("ix_access_credentials_user_id"), "access_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "drops",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("location_type", sa.String(length=16), nullable=False),
        sa.Column("location_label", sa.String(length=200), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("confirmation_seconds", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("rules_version", sa.String(length=32), nullable=False),
        sa.Column("seed_commitment", sa.String(length=64), nullable=True),
        sa.Column("encrypted_seed", sa.LargeBinary(), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column("admission_sequence", sa.Integer(), nullable=False),
        sa.Column("admission_cursor", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("location_type IN ('online','venue')"),
        sa.CheckConstraint("mode IN ('LOTTERY','FCFS_DEMO')"),
        sa.CheckConstraint(
            "phase IN ('DRAFT','SCHEDULED','OPEN','CLOSED','DRAWING','OFFERING','COMPLETED','CANCELLED')"
        ),
        sa.CheckConstraint("capacity BETWEEN 1 AND 500"),
        sa.CheckConstraint("confirmation_seconds BETWEEN 1 AND 604800"),
        sa.CheckConstraint("starts_at < ends_at"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drops_owner_id"), "drops", ["owner_id"], unique=False)
    op.create_index(op.f("ix_drops_phase"), "drops", ["phase"], unique=False)
    op.create_table(
        "idempotency_operations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("key", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("result_kind", sa.String(length=32), nullable=True),
        sa.Column("result_id", sa.Uuid(), nullable=True),
        sa.Column("result_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("status IN ('CLAIMED','COMPLETED')"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "method", "path", "key"),
    )
    op.create_table(
        "lab_runs",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("scenario", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("report_path", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('QUEUED','RUNNING','STOPPING','STOPPED','COMPLETED','FAILED')"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_single_active_lab",
        "lab_runs",
        [sa.literal_column("(1)")],
        unique=True,
        postgresql_where=sa.text("status IN ('QUEUED','RUNNING','STOPPING')"),
    )
    op.create_table(
        "audit_events",
        sa.Column("drop_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=32), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("actor_public_id", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drop_id"],
            ["drops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_drop_id"), "audit_events", ["drop_id"], unique=False)
    op.create_table(
        "draw_runs",
        sa.Column("drop_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("manifest_commitment", sa.String(length=64), nullable=False),
        sa.Column("total_entries", sa.Integer(), nullable=False),
        sa.Column("processed_entries", sa.Integer(), nullable=False),
        sa.Column("next_rank", sa.Integer(), nullable=False),
        sa.Column("recoverable_error", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("status IN ('FROZEN','COMPUTING','PUBLISHED')"),
        sa.CheckConstraint("next_rank > 0"),
        sa.CheckConstraint("total_entries BETWEEN 0 AND 50000"),
        sa.ForeignKeyConstraint(
            ["drop_id"],
            ["drops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("drop_id"),
    )
    op.create_table(
        "eligibility_grants",
        sa.Column("drop_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("credential_id", sa.Uuid(), nullable=True),
        sa.Column("granted_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["access_credentials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["drop_id"],
            ["drops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("drop_id", "user_id"),
        sa.UniqueConstraint("id", "drop_id", "user_id"),
    )
    op.create_table(
        "seat_slots",
        sa.Column("drop_id", sa.Uuid(), nullable=False),
        sa.Column("slot_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("slot_number > 0"),
        sa.ForeignKeyConstraint(
            ["drop_id"],
            ["drops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("drop_id", "slot_number"),
        sa.UniqueConstraint("id", "drop_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("credential_id", sa.Uuid(), nullable=False),
        sa.Column("token_digest", sa.String(length=128), nullable=False),
        sa.Column("csrf_secret", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["access_credentials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_digest"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "entries",
        sa.Column("drop_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("qualifying_grant_id", sa.Uuid(), nullable=False),
        sa.Column("public_entry_id", sa.String(length=64), nullable=False),
        sa.Column("receipt_id", sa.String(length=64), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("admission_sequence", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drop_id"],
            ["drops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["qualifying_grant_id", "drop_id", "user_id"],
            ["eligibility_grants.id", "eligibility_grants.drop_id", "eligibility_grants.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("drop_id", "admission_sequence"),
        sa.UniqueConstraint("drop_id", "user_id"),
        sa.UniqueConstraint("id", "drop_id", "user_id"),
        sa.UniqueConstraint("public_entry_id"),
        sa.UniqueConstraint("receipt_id"),
    )
    op.create_table(
        "frozen_entries",
        sa.Column("draw_id", sa.Uuid(), nullable=False),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("public_entry_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["draw_id"],
            ["draw_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["entries.id"],
        ),
        sa.PrimaryKeyConstraint("draw_id", "entry_id"),
        sa.UniqueConstraint("draw_id", "public_entry_id"),
    )
    op.create_table(
        "reservations",
        sa.Column("drop_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("seat_slot_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("offered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("(status = 'CONFIRMED') = (confirmed_at IS NOT NULL)"),
        sa.CheckConstraint("(status = 'EXPIRED') = (expired_at IS NOT NULL)"),
        sa.CheckConstraint("status IN ('OFFERED','CONFIRMED','EXPIRED')"),
        sa.CheckConstraint("expires_at > offered_at"),
        sa.ForeignKeyConstraint(
            ["drop_id"],
            ["drops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entry_id", "drop_id", "user_id"],
            ["entries.id", "entries.drop_id", "entries.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seat_slot_id", "drop_id"],
            ["seat_slots.id", "seat_slots.drop_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id"),
    )
    op.create_index(
        op.f("ix_reservations_expires_at"), "reservations", ["expires_at"], unique=False
    )
    op.create_index(
        "uq_active_slot",
        "reservations",
        ["drop_id", "seat_slot_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('OFFERED','CONFIRMED')"),
    )
    op.create_index(
        "uq_active_user",
        "reservations",
        ["drop_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('OFFERED','CONFIRMED')"),
    )
    op.create_table(
        "draw_ranks",
        sa.Column("draw_id", sa.Uuid(), nullable=False),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score_bytes", sa.LargeBinary(), nullable=True),
        sa.CheckConstraint("rank > 0"),
        sa.CheckConstraint("score_bytes IS NULL OR octet_length(score_bytes) = 32"),
        sa.ForeignKeyConstraint(
            ["draw_id", "entry_id"],
            ["frozen_entries.draw_id", "frozen_entries.entry_id"],
        ),
        sa.PrimaryKeyConstraint("draw_id", "entry_id"),
        sa.UniqueConstraint("draw_id", "rank"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("draw_ranks")
    op.drop_index(
        "uq_active_user",
        table_name="reservations",
        postgresql_where=sa.text("status IN ('OFFERED','CONFIRMED')"),
    )
    op.drop_index(
        "uq_active_slot",
        table_name="reservations",
        postgresql_where=sa.text("status IN ('OFFERED','CONFIRMED')"),
    )
    op.drop_index(op.f("ix_reservations_expires_at"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_table("frozen_entries")
    op.drop_table("entries")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("seat_slots")
    op.drop_table("eligibility_grants")
    op.drop_table("draw_runs")
    op.drop_index(op.f("ix_audit_events_drop_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(
        "uq_single_active_lab",
        table_name="lab_runs",
        postgresql_where=sa.text("status IN ('QUEUED','RUNNING','STOPPING')"),
    )
    op.drop_table("lab_runs")
    op.drop_table("idempotency_operations")
    op.drop_index(op.f("ix_drops_phase"), table_name="drops")
    op.drop_index(op.f("ix_drops_owner_id"), table_name="drops")
    op.drop_table("drops")
    op.drop_index(op.f("ix_access_credentials_user_id"), table_name="access_credentials")
    op.drop_table("access_credentials")
    op.drop_table("users")
    # ### end Alembic commands ###

    if sa.inspect(op.get_bind()).has_table("users", schema="legacy_security"):
        for table in ("users", "access_credentials", "sessions", "eligibility_grants"):
            op.execute(f"ALTER TABLE legacy_security.{table} SET SCHEMA public")
        op.execute("DROP SCHEMA legacy_security")
    else:
        # An already-stamped M1 database never ran the historical P2 root.
        # Materialize that revision's empty schema when downgrading into it.
        import importlib.util
        from pathlib import Path

        spec = importlib.util.spec_from_file_location(
            "legacy_security_revision", Path(__file__).with_name("0001_security_tables.py")
        )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        module.upgrade()
